server:
  port: 8087

services:
  organization-service:
    id: ORGANIZATION-SERVICE
    v1:
      api: /api/v1/organization-service
      name: ORGANIZATION-SERVICE_V1

  organization-pay:
    id: ORGANIZATION-PAY-SERVICE
    v1:
      api: /api/v1/organizationpay
      name: ORGANIZATION-PAY-SERVICE_V1


spring:
  application:
    name: ORGANIZATION-PAY-SERVICE

  datasource:
    url: jdbc:mysql://myroomawsdb.c3esb8f8pxjo.us-east-1.rds.amazonaws.com/myroom
    username: admin
    password: Devops898

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  kafka:
    bootstrap-servers: ec2-34-234-196-243.compute-1.amazonaws.com:9092
    advertised:
      host:
        name: 34.234.196.243

  main:
    allow-circular-references: true


# Stripe API
stripe:
  api:
    secret-key: secret-key
  endpointSecret: endpointSecret


# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://3.229.47.37:8761/eureka
